<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>spec</string>
	</array>
	<key>name</key>
	<string>Galen</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#general</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*@@\s</string>
			<key>name</key>
			<string>keyword.operator.galen</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(set|import)\b</string>
			<key>name</key>
			<string>support.function.galen</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.galen</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.variable.galen</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.galen</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.galen</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.variable.galen</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.variable.galen</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Section title and tags</string>
			<key>match</key>
			<string>(^@[^@]) *(?:(?:([*^])|(.[^|]+)) *(\|) *(?:([*^])|[-\w, ]+)|(?:([*^])|[-\w, ]+))?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.other.galen</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Specs</string>
			<key>match</key>
			<string>\b(near|below|above|inside( partly)?|width|height|aligned( horizontally(?! (left|right))| vertically(?! (top| bottom))) (all|centered|top|bottom|left|right)|text (is|contains|starts|ends|matches)|css .* (is|starts|ends|contains|matches)|centered (horizontally|vertically|all) (inside|on)|absent|visible|contains( partly)?|on (top|bottom) (left|right)|component|color scheme|image):</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^=+
</string>
			<key>comment</key>
			<string>Object definition</string>
			<key>end</key>
			<string>^=+</string>
			<key>name</key>
			<string>meta.object-definition.galen</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#general</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Locater type</string>
					<key>match</key>
					<string>\b(css|id|xpath)\b</string>
					<key>name</key>
					<string>keyword.other.galen</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.galen</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.galen</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.galen</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.galen</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.galen</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>Object corrections</string>
					<key>match</key>
					<string>\s(@)\(((?:-|\+|=)?\d+), ?((?:-|\+|=)?\d+), ?((?:-|\+|=)?\d+), ?((?:-|\+|=)?\d+)\)\s</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>general</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s*#.*</string>
					<key>name</key>
					<string>comment.line.number-sign.galen</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.galen</string>
	<key>uuid</key>
	<string>a41f12d9-d823-4cb7-9869-508f9a191632</string>
</dict>
</plist>
